### ISSUE TITLE
Long Period Cron Problem

### ISSUE THREAD

**Issue by bsormagec** [emreler/finch#5]
Long period crons stopping after a few days i tried it many times. For example after 3 day all crons enable but i cant see any cron event in mongodb and not running. I dont understand why not working. Maybe response logging will be better for fix that reasons.

Thanks.

**Comment by emreler** [comment]
Is this about the deployment on usefinch.co or are you running it on your own?
Since I'm constantly making changes to the deployment on usefinch.co to make it more stable, it's quite likely things could break time to time.

**Comment by bsormagec** [comment]
Im using it on my own server but after some day its starting to not work more. I didnt find how to fix it.
